package com.xupt.Tool;

public class Template {
    private static final String template = "[{\n" +
            "\t\t        \"weektimes\": \"第一周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第二周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第三周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第四周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第五周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第六周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第七周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第八周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第九周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十一周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十二周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十三周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十四周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十五周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十六周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十七周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    },{\n" +
            "\t\t        \"weektimes\": \"第十八周\",\n" +
            "\t        \t\"firstclass1\": \"\",\n" +
            "\t        \t\"secondclass1\": \"\",\n" +
            "\t        \t\"noon1\": \"\",\n" +
            "\t        \t\"thirdclass1\": \"\",\n" +
            "\t        \t\"fourthclass1\": \"\",\n" +
            "\t        \t\"night1\": \"\",\n" +
            "\t        \t\"firstclass2\": \"\",\n" +
            "\t        \t\"secondclass2\": \"\",\n" +
            "\t        \t\"noon2\": \"\",\n" +
            "\t        \t\"thirdclass2\": \"\",\n" +
            "\t        \t\"fourthclass2\": \"\",\n" +
            "\t        \t\"night2\": \"\",\n" +
            "\t        \t\"firstclass3\": \"\",\n" +
            "\t        \t\"secondclass3\": \"\",\n" +
            "\t        \t\"noon3\": \"\",\n" +
            "\t        \t\"thirdclass3\": \"\",\n" +
            "\t        \t\"fourthclass3\": \"\",\n" +
            "\t        \t\"night3\": \"\",\n" +
            "\t        \t\"firstclass4\": \"\",\n" +
            "\t        \t\"secondclass4\": \"\",\n" +
            "\t        \t\"noon4\": \"\",\n" +
            "\t        \t\"thirdclass4\": \"\",\n" +
            "\t        \t\"fourthclass4\": \"\",\n" +
            "\t        \t\"night4\": \"\",\n" +
            "\t        \t\"firstclass5\": \"\",\n" +
            "\t        \t\"secondclass5\": \"\",\n" +
            "\t        \t\"noon5\": \"\",\n" +
            "\t        \t\"thirdclass5\": \"\",\n" +
            "\t        \t\"fourthclass5\": \"\",\n" +
            "\t        \t\"night5\": \"\"\n" +
            "\t\t    }]";

    public static String getTemplate() {
        return template;
    }
}
